package okf

import (
	"io/fs"
	"path"
	"regexp"
	"strings"
)

// Index is a parsed OKF index.md: the progressive-disclosure entry point
// for a directory (§6). It is the "what's here" an agent can read before
// opening any concept. Index files are never concepts and never indexed for
// search; a Bundle exposes them so a consumer can browse, then query.
//
// Per the spec, index files contain no frontmatter — except the bundle
// root's, the only place frontmatter is permitted (§11), conventionally
// carrying okf_version. The loader still reads frontmatter anywhere
// (permissive consumption); Validate flags the misplaced ones.
type Index struct {
	// Dir is the bundle-relative directory this index describes
	// ("" = bundle root).
	Dir string
	// Title is a display name for the directory: the frontmatter title
	// when one was (non-conformantly but tolerably) present, otherwise the
	// directory's name ("Index" for the root).
	Title string
	// Description is the frontmatter description, if any was present.
	Description string
	// Version is the okf_version declared here (§11). Only the root
	// index.md may declare it.
	Version string
	// Body is the markdown after any frontmatter, verbatim (trimmed).
	Body string
	// Synthesized is true when this Index was generated by
	// Bundle.SynthesizeIndex rather than read from an index.md on disk.
	Synthesized bool

	// fmPresent records whether the file carried a frontmatter block —
	// permitted only at the bundle root (§11); Validate checks it.
	fmPresent bool
	// fmTitle / fmDesc are the raw frontmatter values (as opposed to the
	// derived Title), so Marshal writes back only what was really there.
	fmTitle, fmDesc string
}

// Log is a parsed OKF log.md: a directory's change history (§7). Entries
// are grouped under ISO-8601 date headings, newest first; each entry is a
// list item, conventionally starting with a bold kind marker
// (**Update**, **Creation**, ...). Logs never touch retrieval.
type Log struct {
	// Dir is the bundle-relative directory this log belongs to
	// ("" = bundle root).
	Dir string
	// Entries are the changelog rows, in file order.
	Entries []LogEntry

	// badDates collects `##` headings that are not ISO-8601 dates — §7
	// says date headings MUST be YYYY-MM-DD; Validate reports them.
	badDates []string
	// undated counts list items appearing before any date heading;
	// Validate reports them as a structure warning.
	undated int
}

// LogEntry is one item of a log.md changelog. Timestamp is the ISO-8601
// date of the `##` heading the entry appears under (or a per-entry
// timestamp when the item leads with one); empty if the entry is outside
// any date group. Kind is the conventional bold marker (`**Update**:` ->
// "Update"), empty when the entry doesn't use the convention.
type LogEntry struct {
	Timestamp string
	Kind      string
	Text      string
}

// okfVersionKey is the frontmatter field carrying the spec revision (§11).
const okfVersionKey = "okf_version"

var (
	// logItemRe matches a markdown list item ("- ..." or "* ...").
	logItemRe = regexp.MustCompile(`^\s*[-*]\s+(.*)$`)
	// logDateRe matches a `## <date>` heading of a log.md (§7).
	logDateRe = regexp.MustCompile(`^##\s+(.+?)\s*$`)
	// isoDateRe is §7's required YYYY-MM-DD date-heading form.
	isoDateRe = regexp.MustCompile(`^\d{4}-\d{2}-\d{2}$`)
	// kindRe pulls the conventional bold kind marker off a log entry:
	// "**Update**: rest" -> Update, rest.
	kindRe = regexp.MustCompile(`^\*\*([^*]+)\*\*:?\s*(.*)$`)
	// leadingTSRe pulls an optional leading ISO-8601 timestamp off a log
	// entry (a tolerated flat-list variant), allowing ":", "-" or "—" as
	// the separator before the text.
	leadingTSRe = regexp.MustCompile(`^(\d{4}-\d{2}-\d{2}(?:[T ]\d{2}:\d{2}(?::\d{2})?(?:Z|[+-]\d{2}:\d{2})?)?)\s*[:—-]?\s*(.*)$`)
)

// parseIndexFile reads and parses one index.md into an Index. A read error
// is downgraded to a warning (permissive consumption); the returned Index
// still carries its Dir so the bundle records that the file exists.
func parseIndexFile(fsys fs.FS, root, p string) (Index, []string) {
	dir := dirOf(root, p)
	data, err := fs.ReadFile(fsys, p)
	if err != nil {
		return Index{Dir: dir}, []string{p + ": " + err.Error()}
	}
	fmText, body, present := splitFrontmatter(string(data))
	fm := parseFrontmatter(fmText)
	idx := Index{
		Dir:         dir,
		Title:       asString(fm, MetaTitle),
		Description: asString(fm, MetaDesc),
		Version:     asString(fm, okfVersionKey),
		Body:        strings.TrimSpace(body),
		fmPresent:   present,
		fmTitle:     asString(fm, MetaTitle),
		fmDesc:      asString(fm, MetaDesc),
	}
	if idx.Title == "" {
		idx.Title = dirTitle(dir)
	}
	return idx, nil
}

// parseLogFile reads and parses one log.md into a Log. The §7 format is
// date-grouped: `## YYYY-MM-DD` headings, newest first, each followed by
// list items ("* **Update**: ..."). Parsing is permissive — a flat list
// item leading with its own timestamp is tolerated, non-ISO date headings
// are recorded for Validate rather than rejected, and anything that is
// neither a heading nor a list item is ignored.
func parseLogFile(fsys fs.FS, root, p string) (Log, []string) {
	dir := dirOf(root, p)
	data, err := fs.ReadFile(fsys, p)
	if err != nil {
		return Log{Dir: dir}, []string{p + ": " + err.Error()}
	}
	_, body, _ := splitFrontmatter(string(data))
	lg := Log{Dir: dir}
	currentDate := ""
	for _, line := range strings.Split(body, "\n") {
		if m := logDateRe.FindStringSubmatch(line); m != nil {
			d := strings.TrimSpace(m[1])
			if isoDateRe.MatchString(d) {
				currentDate = d
			} else {
				lg.badDates = append(lg.badDates, d)
				currentDate = ""
			}
			continue
		}
		m := logItemRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		item := strings.TrimSpace(m[1])
		if item == "" {
			continue
		}
		entry := LogEntry{Timestamp: currentDate}
		// Flat-list tolerance: an item carrying its own leading timestamp.
		if ts := leadingTSRe.FindStringSubmatch(item); ts != nil && ts[1] != "" {
			entry.Timestamp = ts[1]
			item = strings.TrimSpace(ts[2])
		}
		if k := kindRe.FindStringSubmatch(item); k != nil {
			entry.Kind = strings.TrimSpace(k[1])
			item = strings.TrimSpace(k[2])
		}
		entry.Text = item
		if entry.Timestamp == "" {
			lg.undated++
		}
		lg.Entries = append(lg.Entries, entry)
	}
	return lg, nil
}

// SynthesizeIndex builds an Index for a directory on the fly, for when no
// index.md exists (§6 lets a consumer synthesize progressive disclosure).
// The body follows §6's entry format — `* [Title](relative-url) - short
// description` — listing the immediate subdirectories first, then the
// direct-child concepts, with links relative to the directory and each
// concept's frontmatter description. dir is bundle-relative ("" = root).
//
// It considers only direct children, not the whole subtree, so a
// synthesized index mirrors what a real index.md conventionally lists.
func (b *Bundle) SynthesizeIndex(dir string) Index {
	dir = normalizeDir(dir)
	title := dirTitle(dir)
	subdirs := b.Dirs(dir)
	children := b.Children(dir)
	lines := make([]string, 0, 2+len(subdirs)+len(children))
	lines = append(lines, "# "+title, "")
	for _, sub := range subdirs {
		lines = append(lines, "* ["+lastSegment(sub)+"]("+lastSegment(sub)+"/)")
	}
	for _, id := range children {
		c, _ := b.Concept(id)
		entryTitle := c.Metadata[MetaTitle]
		if entryTitle == "" {
			entryTitle = lastSegment(id)
		}
		line := "* [" + entryTitle + "](" + lastSegment(id) + ".md)"
		if desc := c.Metadata[MetaDesc]; desc != "" {
			line += " - " + desc
		}
		lines = append(lines, line)
	}
	return Index{
		Dir:         dir,
		Title:       title,
		Body:        strings.TrimSpace(strings.Join(lines, "\n")),
		Synthesized: true,
	}
}

// IndexFor returns the directory's index.md when present, otherwise a
// synthesized one (Index.Synthesized == true). dir is bundle-relative.
func (b *Bundle) IndexFor(dir string) Index {
	dir = normalizeDir(dir)
	if idx, ok := b.Indexes[dir]; ok {
		return idx
	}
	return b.SynthesizeIndex(dir)
}

// dirTitle is the display name for a directory: its last path segment, or
// "Index" for the bundle root.
func dirTitle(dir string) string {
	if dir == "" {
		return "Index"
	}
	return lastSegment(dir)
}

// dirOf returns the bundle-relative directory of a reserved file path
// ("" = root).
func dirOf(root, p string) string {
	rel := relTo(root, p)
	return dirOfID(strings.TrimSuffix(rel, ".md"))
}

// dirOfID returns the parent directory of a concept id ("" = root).
func dirOfID(id string) string {
	d := path.Dir(id)
	if d == "." || d == "/" {
		return ""
	}
	return d
}

// normalizeDir maps the various spellings of "the bundle root" (".", "/")
// to "" and strips a trailing slash, so callers can pass whatever is handy.
func normalizeDir(dir string) string {
	if dir == "." || dir == "/" {
		return ""
	}
	return strings.TrimSuffix(dir, "/")
}
