// Package tool provides the type-safe tool system used by galdor agents.
//
// A tool is a generic Tool[In, Out] with a JSON Schema generated by
// reflection from In, executed concurrently when the LLM emits multiple
// tool calls.
//
// Status: stub (Phase 2).
package tool
