package tool

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/YasserCR/galdor/internal/jsonschema"
)

// Tool is the typed tool interface a caller works with. Generic
// parameters preserve compile-time safety on Execute. Use the type-
// erased AnyTool when storing tools in collections or dispatching
// dynamically by name.
type Tool[In any, Out any] interface {
	AnyTool
	Execute(ctx context.Context, input In) (Out, error)
}

// AnyTool is the type-erased view used by Registry, executors, and
// adapters that translate to provider-side tool definitions. Every
// concrete Tool[In, Out] also implements AnyTool.
type AnyTool interface {
	Name() string
	Description() string
	Schema() *jsonschema.Schema

	// ExecuteJSON runs the tool with raw JSON input and returns the
	// JSON-marshaled output. Adapters and the executor use this path
	// because they only see schema.ToolCall.Arguments (a json.RawMessage)
	// and need to ship results back the same way.
	ExecuteJSON(ctx context.Context, input json.RawMessage) (json.RawMessage, error)
}

// ErrInvalidInput is returned by ExecuteJSON when the raw input fails to
// decode into the tool's In type. Callers can use errors.Is to detect it
// and surface a user-friendly retry hint to the model.
var ErrInvalidInput = errors.New("tool: invalid input")

// NewTool builds a tool whose JSON Schema is generated by reflection on
// the In type. The returned value implements both Tool[In, Out] (typed)
// and AnyTool (erased). Returns an error if the schema cannot be
// derived from In (recursive types, unsupported kinds, etc.).
func NewTool[In any, Out any](
	name, description string,
	fn func(ctx context.Context, input In) (Out, error),
) (Tool[In, Out], error) {
	if name == "" {
		return nil, errors.New("tool: Name is required")
	}
	if fn == nil {
		return nil, errors.New("tool: fn is required")
	}
	schema, err := jsonschema.For[In]()
	if err != nil {
		return nil, fmt.Errorf("tool %q: %w", name, err)
	}
	return &typedTool[In, Out]{
		name:        name,
		description: description,
		schema:      schema,
		fn:          fn,
	}, nil
}

// MustNewTool is the panicking variant of NewTool. Convenient for tools
// declared as package-level vars where a schema-generation failure
// would be a programmer error caught at startup, not a runtime error.
func MustNewTool[In any, Out any](
	name, description string,
	fn func(ctx context.Context, input In) (Out, error),
) Tool[In, Out] {
	t, err := NewTool(name, description, fn)
	if err != nil {
		panic(err)
	}
	return t
}

type typedTool[In any, Out any] struct {
	name        string
	description string
	schema      *jsonschema.Schema
	fn          func(ctx context.Context, input In) (Out, error)
}

func (t *typedTool[In, Out]) Name() string               { return t.name }
func (t *typedTool[In, Out]) Description() string        { return t.description }
func (t *typedTool[In, Out]) Schema() *jsonschema.Schema { return t.schema }
func (t *typedTool[In, Out]) Execute(ctx context.Context, in In) (Out, error) {
	return t.fn(ctx, in)
}

// ExecuteJSON is the erased entry point. It decodes raw into In, runs
// the tool, and marshals the result. Decode failures are returned
// wrapped in ErrInvalidInput.
func (t *typedTool[In, Out]) ExecuteJSON(ctx context.Context, raw json.RawMessage) (json.RawMessage, error) {
	var in In
	// Allow empty/nil input — many tools take no arguments. The zero
	// value of In is what they get.
	if len(raw) > 0 && string(raw) != "null" {
		if err := json.Unmarshal(raw, &in); err != nil {
			return nil, fmt.Errorf("%w: %s", ErrInvalidInput, err.Error())
		}
	}
	out, err := t.fn(ctx, in)
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}
